
### Link with compiler-libs stuff ###

CAMLFLAGS += -I +compiler-libs

compilerlibs.cmxs: fake_terminfo.c
	$(CAMLOPTLINK) $(CAMLFLAGS) -linkall -shared -o $@ ocamlcommon.cmxa ocamloptcomp.cmxa $^

ExtractionCompute.vo: compilerlibs.cmxs

clean::
	rm -rf fake_terminfo.o compilerlibs.cmxs

# For emacs:
# Local Variables:
# mode: makefile
# End:
